### ISSUE TITLE
Forwarder restarts with FATAL error in case of registry and nsmgr reboot

### ISSUE THREAD

**Issue by richardstone** [networkservicemesh/cmd-forwarder-vpp#435] opened 2021-12-08 15:05 UTC
At first the issue popped up during an upgrade test in which we try to upgrade NSM from a pre v1.1.1 version to NSM v1.1.1
It is an intermittent issue (timing is key), but can be reporoduced with simple pod restarts by "kubectl delete pod XY --force".

NSM elements gets restarted  in the following order:
1. Forwarder restart
2. Registry restart
3. NSMgr restart

I was able to reproduce the issue with this timing:
forwarder restart -> sleep 2.5 -> registry restart -> sleep 2 -> NSMgr restart

By issueing different timing for the restarts, heal function looks to be working great, keeping everything up and running, waiting for connections, etc..

I attached the logs of the forwarder. Unfortunately logs from the "old" registry and NSMgr are not available due to them being killed.
The timing to reporoduce the issue might differ for you according to the available resources for the k8s cluster, I tried it on kind.
[forwarder.log](https://github.com/networkservicemesh/cmd-forwarder-vpp/files/7676917/forwarder.log)

**Comment by edwarnicke** [comment] 2021-12-08 15:13
@richardstone Thanks for finding this.

@denis-tingaikin @glazychev-art Any ideas?

**Comment by denis-tingaikin** [comment] 2021-12-08 19:57
This is a good catch. We'll consider the FATAL problem within https://github.com/networkservicemesh/sdk/issues/1170

Moreover, we're planning to add advanced healing when two components die. @glazychev-art Could you remind issue number?

**Comment by edwarnicke** [comment] 2021-12-09 22:01
@richardstone Looking at that logs and the code, this looks like the Forwarder is in the process of starting up and hits:

https://github.com/networkservicemesh/cmd-forwarder-vpp/blob/6898affa3cc9b85a47777e724b60618af6c5fa24/main.go#L252-L254

Due to not being able to register with the Registry on startup (probably because the NSMgr isn't running yet).

Normally, the Forwarder would restart until the NSMgr is available to be registered with and then everything would converge... did that happen for you?

While we could consider other, potentially more graceful ways of handling this situation, it is the case that things should converge no matter what order the Forwarder, NSMgr, etc start in.  If that's not happening, I'm very concerning bug.  If convergence isn't happening *fast* enough, I'm quite open to talking about that as well, but would be curious if you have a notion of how fast you need it to be :)

**Comment by richardstone** [comment] 2021-12-10 08:14
@edwarnicke In my case everything started to work just fine, shortly after the unexpected restart of the forwarder.

My concern is not about the time until we reach convergence in these cases, but the unexpected restart of the forwarder when it's unable to reach certain NSM components at the right time.
I'm okay with a bit slower start time for the new instance, so that it can wait - instead of restart - until it's able to reach every component.

**Comment by edwarnicke** [comment] 2021-12-10 16:21
@richardstone 
> @edwarnicke In my case everything started to work just fine, shortly after the unexpected restart of the forwarder.

Glad everything started to work just fine :)  That's the behavior I would expect.

> My concern is not about the time until we reach convergence in these cases, but the unexpected restart of the forwarder when it's unable to reach certain NSM components at the right time. I'm okay with a bit slower start time for the new instance, so that it can wait - instead of restart - until it's able to reach every component.

I tend to think about this in layers:
1. This is all working as designed... which is not to assert the design is correct :)
2. The restart only happens if the registry isn't available *initially* to the Forwarder, if  the registry *disappears* after becoming initially available, the Forwarder should be fine.
3. Alarming users is not cool, even if things eventually end up being OK, so I'm very open to talking about less alarming ways to do this.

What would make this less alarming to you?

**Comment by richardstone** [comment] 2021-12-13 12:40
@edwarnicke 

The most alarming thing to me is that the forwarder restarted as soon as it faced a connection loss. If It could wait for a certain timeout (configurable) that would be the best, so if it get's connected to the other components within the specified timeout then everything is fine. In any other case it is free to restart, so the user gets notified about a - probably - bigger issue with the connection. 

This should apply to every NSM component in my opinion.

**Comment by edwarnicke** [comment] 2021-12-14 12:55
@richardstone Any chance you would be in the community meeting today (Tue) at 8am PT to discuss?

**Comment by richardstone** [comment] 2021-12-14 12:56
@edwarnicke Sure. Meet you there :)

**Comment by denis-tingaikin** [comment] 2022-01-24 04:54
Should be fixed with Implement 'retry' registry chain element networkservicemesh/sdk#1201

@richardstone Be free to reopen this issue if it will reporduciable!

**Closed by denis-tingaikin** 2022-01-24 04:54 UTC
Labels: bug
