### ISSUE TITLE
worker node interface MTU arbitrarily increased

### ISSUE THREAD

**Issue by zolug** [networkservicemesh/cmd-forwarder-vpp#557] opened 2022-04-06 17:19 UTC
MTU of the node interface hosting NSM_TUNNEL_IP raised from initial 1500 bytes when using vpp-forwarder v1.3.0-rc.1 (AF_PACKET mode).
Thus causing traffic disturbances if the "base" interface (e.g. tap) MTU is 1500 bytes on the host.

Mostly the new value ends up being 1544 bytes (but in one occasion it turned out to be 1588 bytes).
Also, in case there are multiple network interfaces on the VM, their MTU might get changed as well even though TUNNEL_IP is not hosted by them. (I guess it's because I have a _DeviceSelectorFile_ configured as well. Although occasionally not all the devices in the file are affected by the MTU change).

Interface MTUs are left intact when running with vpp-forwarder v1.2.0.
Also, when rebuilt with the VPP version used in v1.2.0, the problem does not appear.

To reproduce:
- example 'basic' or 'memory' should do (there's no need to deploy any NSC or NSE)
- Kind can be used as well

IPv4 traffic impact can be verified simply with netcat (assuming the new MTU is 1544 bytes):
- Create a TCP server on one of the worker nodes listening on an address that belongs to the affected interface (pick a server port of your liking)
- Create TCP client connecting to the listener set up in the previous step, and try to send e.g. 1480 bytes payload. The data will never reach the server. Running tcpdump on the client side reveals the retransmits.
(Note: If TCP TX segmentation offload is enabled, then TCP payload sizes exceeding (NEW_MTU - (IPv4_header_size + TCP_overhead_including_options)) will succeed.)

k8s impact:
If _kube-apiserver_ is running on a VM that also hosts a vpp-forwarder, then kubernetes API server requests from other nodes might randomly fail resulting in the following error:

> vm-002 ~ # kubectl get pods -n nsm
E0406 17:32:54.015653   15189 request.go:1085] Unexpected error when reading response body: http2: client connection lost
unexpected error when reading response body. Please retry. Original error: http2: client connection lost

[mtu.txt](https://github.com/networkservicemesh/cmd-forwarder-vpp/files/8429033/mtu.txt)

**Comment by zolug** [comment] 2022-04-08 11:13
Got a hint from @ljkiraly that instead of _HwInterfaceSetMtu_ vpp API call _SwInterfaceSetMtu_ might be more feasible.
Gave it a try and interface MTUs were left intact, and things seemed to work fine.
[diff.txt](https://github.com/networkservicemesh/cmd-forwarder-vpp/files/8451311/diff.txt)

**Comment by edwarnicke** [comment] 2022-04-11 13:47
@ljkiraly Could you say more about the cases in which the mtu chain element could interfere?

**Comment by zolug** [comment] 2022-04-11 14:27
> @zolug OK... so it looks like the root issue here is that the VPP MTU is resulting in setting the interface MTU (and incorrectly). Is that right?

Yes, that's correct.

**Comment by ljkiraly** [comment] 2022-04-11 14:40
@edwarnicke 
First of all the main issue is that the [HwInterfaceSetMtu](https://pkg.go.dev/github.com/edwarnicke/govpp/binapi/interface?utm_source=gopls#RPCService.HwInterfaceSetMtu) binapi RPC changed it's behavior. I do not know the reason behind this, so that's why we not tried to fix this by changing to [SwInterfaceSetMtu](https://pkg.go.dev/github.com/edwarnicke/govpp/binapi/interface?utm_source=gopls#RPCService.SwInterfaceSetMtu).

At the startup of the forwarder the initialization function will set the MTU  first and add 44 bytes to the given interface (e.g the interface given by IP_TUNNEL address, with default 1500 MTU will be set to 1544). Then the ConnectionContext will try to adjust the MTU and calls the  HwInterfaceSetMtu again increasing the MTU value with 44 bytes (resulting in 1588). I suppose that will keep increasing when the forwarder restarts.

**Comment by edwarnicke** [comment] 2022-04-11 14:58
@ljkiraly Got it, so we need to simply switch from HwInterfaceSetMtu to SwInterfaceSetMtu where ever it is used.

**Comment by ljkiraly** [comment] 2022-04-11 15:22
@edwarnicke I'm not sure about the ConnectionContext, since there are two functions: [setVPPL2MTU](https://github.com/networkservicemesh/sdk-vpp/blob/5cb7919d7814d5079e68b6d62c39b00dd10d6d89/pkg/networkservice/connectioncontext/mtu/common.go#L37) and [setVPPL3MTU](https://github.com/networkservicemesh/sdk-vpp/blob/5cb7919d7814d5079e68b6d62c39b00dd10d6d89/pkg/networkservice/connectioncontext/mtu/common.go#L66).
- layer2 calls HwInterfaceSetMtu
- layer3 calls SwInterfaceSetMtu.
I don't know the original intention behind this division.

**Comment by zolug** [comment] 2022-04-11 16:25
@edwarnicke

> do we anticipate needing to pass 802.1q tagged ethernet frames over VXLAN
No, we don't.

**Comment by edwarnicke** [comment] 2022-04-11 18:06
@ljkiraly @denis-tingaikin @zolug Could you have a look at these fixes:

https://github.com/networkservicemesh/cmd-forwarder-vpp/pull/569

https://github.com/networkservicemesh/sdk-vpp/pull/554

**Comment by edwarnicke** [comment] 2022-04-11 18:07
@ljkiraly I am looking at https://github.com/networkservicemesh/sdk-vpp/blob/c508e185a1f11ba6f44f7f8c5b60850a0db8d1bb/pkg/networkservice/mechanisms/vlan/mtu/common.go#L31-L51 and trying to decide what the right thing to do is.

**Comment by zolug** [comment] 2022-04-11 20:11
@edwarnicke Thanks! The fixes work without any problem.

The following log msg printed on forwarder start is a bit misleading though now:
> [MTU:[1500 1500 1500 1500]] [cmd:/bin/forwarder] [duration:155.192µs] [swIfIndex:1] [vppapi:**HwInterfaceSetMtu**]

**Comment by edwarnicke** [comment] 2022-04-11 22:45
> @edwarnicke Thanks! The fixes work without any problem.
> 
> The following log msg printed on forwarder start is a bit misleading though now:
> 
> > [MTU:[1500 1500 1500 1500]] [cmd:/bin/forwarder] [duration:155.192µs] [swIfIndex:1] [vppapi:**HwInterfaceSetMtu**]

@zolug This should be fixed in https://github.com/networkservicemesh/cmd-forwarder-vpp/pull/570 - thank you for catching it :)

**Comment by ljkiraly** [comment] 2022-04-12 08:22
@edwarnicke I propose to simply get L3 MTU since is set based on L2 link MTU and should not modified elsewhere. Check networkservicemesh/sdk-vpp#555

**Comment by edwarnicke** [comment] 2022-04-12 13:56
@ljkiraly Have you confirmed that the L3 MTU is *set* for the interfaces you care about (in the absence of setting it yourself?).  I ask, because for software interfaces (like af packet) its not.

**Closed** 2022-06-02 13:17 UTC
Labels: bug
